// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH6Agvf5HUX6-mCD2IGOG2YJr4pCpiVxo',
    appId: '1:572696700406:web:d70f5a51f596ec9c28d3d7',
    messagingSenderId: '572696700406',
    projectId: 'database-ypbic',
    authDomain: 'database-ypbic.firebaseapp.com',
    storageBucket: 'database-ypbic.firebasestorage.app',
    measurementId: 'G-R234L318W6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhOpawbYUucFxx7TZsa0TMW007nDH_hDs',
    appId: '1:572696700406:android:284d8fc504238dda28d3d7',
    messagingSenderId: '572696700406',
    projectId: 'database-ypbic',
    storageBucket: 'database-ypbic.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH6Agvf5HUX6-mCD2IGOG2YJr4pCpiVxo',
    appId: '1:572696700406:web:f9d7f55d93caf37328d3d7',
    messagingSenderId: '572696700406',
    projectId: 'database-ypbic',
    authDomain: 'database-ypbic.firebaseapp.com',
    storageBucket: 'database-ypbic.firebasestorage.app',
    measurementId: 'G-HMKLWT5VGN',
  );
}
